/**
 * PULSE-078 source-reconciliation installer and read-only runner.
 *
 * First run forgeCreatePulse078SourceReconciliationPullRequest().
 * After that PR is manually merged, run forgePulse078RunSourceReconciliation().
 *
 * No automatic merge, Apps Script production write, deployment, or engine activation.
 */

function forgeCreatePulse078SourceReconciliationPullRequest() {
  const runnerPath = 'pulse-forge/controller/PULSE078SourceReconciliation.gs';
  const testPath = 'pulse-forge/tests/validate-pulse-078.mjs';
  const taskPath = 'pulse-agent/tasks/PULSE-078.json';
  const packagePath = 'pulse-forge/package.json';

  const packageText = forgePulse078InstallerReadRepoText_(packagePath, 'main');
  const packageJson = JSON.parse(packageText);
  packageJson.version = '0.3.0';
  packageJson.scripts = packageJson.scripts || {};
  const currentValidation = String(packageJson.scripts.validate || '').trim();
  const pulse078Command = 'node tests/validate-pulse-078.mjs';
  packageJson.scripts.validate = currentValidation.indexOf(pulse078Command) >= 0
    ? currentValidation
    : (currentValidation ? currentValidation + ' && ' : '') + pulse078Command;

  const stamp = Utilities.formatDate(
    new Date(),
    Session.getScriptTimeZone() || 'America/New_York',
    'yyyyMMdd-HHmmss'
  );

  const result = forgeGitHubCreatePullRequest({
    baseBranch: 'main',
    headBranch: 'pulse/pulse-078-source-reconciliation-framework-' + stamp,
    title: 'PULSE-078: Add live-source reconciliation',
    commitMessage: 'Add read-only Pulse live-source reconciliation',
    body: [
      '## PULSE-078 source reconciliation framework',
      '',
      'Adds a read-only controller task that reads complete live Apps Script source,',
      'classifies every mapped file as MATCH, DIFF, LIVE_ONLY, or REPO_ONLY,',
      'captures immutable source snapshots and hashes, and proposes live application',
      'drift through a reviewed GitHub pull request.',
      '',
      '### Source authority',
      '- Forge controller: repository preferred',
      '- Hoy Driver, request app, and rider-status runtime: live source preferred',
      '- The standalone request app remains the only declared Ride Requests writer',
      '',
      '### Safety',
      '- No Apps Script HEAD writes',
      '- No deployments',
      '- No engine activation',
      '- No automatic merge',
      '- No production data mutation'
    ].join('\n'),
    files: [
      {
        path: runnerPath,
        content: forgePulse078InstallerDecode_('LyoqCiAqIFBVTFNFLTA3OCDigJQgcmVhZC1vbmx5IGxpdmUtc291cmNlIHJlY29uY2lsaWF0aW9uLgogKgogKiBSZWFkcyBjb21wbGV0ZSBBcHBzIFNjcmlwdCBIRUFEIHNvdXJjZSwgY29tcGFyZXMgaXQgd2l0aCBHaXRIdWIsIGNhcHR1cmVzCiAqIGltbXV0YWJsZSBwZXItZmlsZSBoYXNoZXMgYW5kIHNvdXJjZSBzbmFwc2hvdHMsIGFuZCBvcGVucyBhIHJldmlld2VkIFBSLgogKiBJdCBuZXZlciB3cml0ZXMgQXBwcyBTY3JpcHQgSEVBRCwgY3JlYXRlcyBhIGRlcGxveW1lbnQsIGFjdGl2YXRlcyBhbiBlbmdpbmUsCiAqIG1lcmdlcyBhIFBSLCBvciBjaGFuZ2VzIHByb2R1Y3Rpb24gZGF0YS4KICovCgpjb25zdCBGT1JHRV9QVUxTRTA3OF9UQVNLX0lEXyA9ICdQVUxTRS0wNzgnOwpjb25zdCBGT1JHRV9QVUxTRTA3OF9MQVRFU1RfUkVDRUlQVF9LRVlfID0gJ1BVTFNFX0ZPUkdFX1BVTFNFMDc4X0xBVEVTVF9SRUNFSVBUJzsKY29uc3QgRk9SR0VfUFVMU0UwNzhfUkVDRUlQVF9QUkVGSVhfID0gJ1BVTFNFX0ZPUkdFX1BVTFNFMDc4X1JFQ0VJUFRfJzsKCmZ1bmN0aW9uIGZvcmdlUHVsc2UwNzhUYXJnZXRzXygpIHsKICByZXR1cm4gWwogICAgewogICAgICBhbGlhczogJ0ZPUkdFX0NPTlRST0xMRVInLAogICAgICBzY3JpcHRJZDogU2NyaXB0QXBwLmdldFNjcmlwdElkKCksCiAgICAgIHJlcG9Sb290czogWydwdWxzZS1mb3JnZS9jb3JlLycsICdwdWxzZS1mb3JnZS9jb250cm9sbGVyLyddLAogICAgICByZXBvRXhhY3Q6IFsncHVsc2UtZm9yZ2UvYXBwc3NjcmlwdC5qc29uJ10sCiAgICAgIGNhbm9uaWNhbFJvb3Q6ICdwdWxzZS1mb3JnZS9jb250cm9sbGVyJywKICAgICAgYXV0aG9yaXR5OiAnUkVQTycsCiAgICAgIHJpZGVSZXF1ZXN0c1dyaXRlcjogZmFsc2UsCiAgICAgIGltcG9ydExpdmVPbmx5OiBmYWxzZSwKICAgICAgY29udHJvbGxlclByb2plY3Q6IHRydWUKICAgIH0sCiAgICB7CiAgICAgIGFsaWFzOiAnSE9ZX0RSSVZFUicsCiAgICAgIHNjcmlwdElkOiAnMXNON01GcnpFT0QwR01JT2MxMFhvQThqNUlQelp3UXlub3dJdVpwWERDV3VMYkYyd3FJRGY4WmowJywKICAgICAgcmVwb1Jvb3RzOiBbJ2FwcHMtc2NyaXB0L2hveS1kcml2ZXItb3Mtd3JpdGVyLyddLAogICAgICByZXBvRXhhY3Q6IFtdLAogICAgICBjYW5vbmljYWxSb290OiAnYXBwcy1zY3JpcHQvaG95LWRyaXZlci1vcy13cml0ZXInLAogICAgICBhdXRob3JpdHk6ICdMSVZFJywKICAgICAgcmlkZVJlcXVlc3RzV3JpdGVyOiBmYWxzZSwKICAgICAgaW1wb3J0TGl2ZU9ubHk6IHRydWUsCiAgICAgIGNvbnRyb2xsZXJQcm9qZWN0OiBmYWxzZQogICAgfSwKICAgIHsKICAgICAgYWxpYXM6ICdQVUxTRV9SRVFVRVNUX0FQUCcsCiAgICAgIHNjcmlwdElkOiAnMXB4Ri10cWx1LU5ySU52MFFELXNRWkVYTUdVb2M0MDhZaEhPdUtjY29VX1VSQ3RDeU9tVGlhVlNtJywKICAgICAgcmVwb1Jvb3RzOiBbJ3B1bHNlLWF1dG9idWlsZC9yZXF1ZXN0LWFwcC8nXSwKICAgICAgcmVwb0V4YWN0OiBbXSwKICAgICAgY2Fub25pY2FsUm9vdDogJ3B1bHNlLWF1dG9idWlsZC9yZXF1ZXN0LWFwcCcsCiAgICAgIGF1dGhvcml0eTogJ0xJVkUnLAogICAgICByaWRlUmVxdWVzdHNXcml0ZXI6IHRydWUsCiAgICAgIGltcG9ydExpdmVPbmx5OiB0cnVlLAogICAgICBjb250cm9sbGVyUHJvamVjdDogZmFsc2UKICAgIH0sCiAgICB7CiAgICAgIGFsaWFzOiAnUklERVJfU1RBVFVTX1JVTlRJTUUnLAogICAgICBzY3JpcHRJZDogJzFjQUJJenYwajhwb1lHeTNoVmJjbUtlLURCdUpRSFI5SGNqLTJsOVZxdlhNb3Rfa21sZUtuSGdVZicsCiAgICAgIHJlcG9Sb290czogWydwdWxzZS1hdXRvYnVpbGQvcnVudGltZS8nXSwKICAgICAgcmVwb0V4YWN0OiBbXSwKICAgICAgY2Fub25pY2FsUm9vdDogJ3B1bHNlLWF1dG9idWlsZC9ydW50aW1lJywKICAgICAgYXV0aG9yaXR5OiAnTElWRScsCiAgICAgIHJpZGVSZXF1ZXN0c1dyaXRlcjogZmFsc2UsCiAgICAgIGltcG9ydExpdmVPbmx5OiB0cnVlLAogICAgICBjb250cm9sbGVyUHJvamVjdDogZmFsc2UKICAgIH0KICBdOwp9CgpmdW5jdGlvbiBmb3JnZVB1bHNlMDc4QXNzZXJ0V3JpdGVyQm91bmRhcnlfKHRhcmdldHMpIHsKICBjb25zdCB3cml0ZXJzID0gKHRhcmdldHMgfHwgW10pLmZpbHRlcihmdW5jdGlvbih0YXJnZXQpIHsKICAgIHJldHVybiB0YXJnZXQucmlkZVJlcXVlc3RzV3JpdGVyID09PSB0cnVlOwogIH0pOwogIGZvcmdlQXNzZXJ0Xyh3cml0ZXJzLmxlbmd0aCA9PT0gMSwgJ0V4YWN0bHkgb25lIFJpZGUgUmVxdWVzdHMgd3JpdGVyIG11c3QgYmUgZGVjbGFyZWQuJyk7CiAgZm9yZ2VBc3NlcnRfKAogICAgd3JpdGVyc1swXS5hbGlhcyA9PT0gJ1BVTFNFX1JFUVVFU1RfQVBQJywKICAgICdUaGUgc3RhbmRhbG9uZSBQdWxzZSBSZXF1ZXN0IEFwcCBtdXN0IHJlbWFpbiB0aGUgb25seSBSaWRlIFJlcXVlc3RzIHdyaXRlci4nCiAgKTsKICByZXR1cm4gewogICAgb2s6IHRydWUsCiAgICBhdXRob3JpemVkV3JpdGVyQWxpYXM6IHdyaXRlcnNbMF0uYWxpYXMsCiAgICBhZGRpdGlvbmFsV3JpdGVyc0RlY2xhcmVkOiBmYWxzZQogIH07Cn0KCmZ1bmN0aW9uIGZvcmdlUHVsc2UwNzhGaWxlSWRlbnRpdHlfKGZpbGUpIHsKICByZXR1cm4gZm9yZ2VTdHJpbmdfKGZpbGUubmFtZSkudG9Mb3dlckNhc2UoKSArICc6OicgKyBmb3JnZVN0cmluZ18oZmlsZS50eXBlKS50b1VwcGVyQ2FzZSgpOwp9CgpmdW5jdGlvbiBmb3JnZVB1bHNlMDc4RXh0ZW5zaW9uXyh0eXBlKSB7CiAgY29uc3Qgbm9ybWFsaXplZCA9IGZvcmdlU3RyaW5nXyh0eXBlKS50b1VwcGVyQ2FzZSgpOwogIGlmIChub3JtYWxpemVkID09PSAnU0VSVkVSX0pTJykgcmV0dXJuICcuZ3MnOwogIGlmIChub3JtYWxpemVkID09PSAnSFRNTCcpIHJldHVybiAnLmh0bWwnOwogIGlmIChub3JtYWxpemVkID09PSAnSlNPTicpIHJldHVybiAnLmpzb24nOwogIHRocm93IG5ldyBFcnJvcignVW5zdXBwb3J0ZWQgQXBwcyBTY3JpcHQgZmlsZSB0eXBlOiAnICsgbm9ybWFsaXplZCk7Cn0KCmZ1bmN0aW9uIGZvcmdlUHVsc2UwNzhSZXBvSWRlbnRpdHlGcm9tUGF0aF8ocGF0aCkgewogIGNvbnN0IGNsZWFuID0gZm9yZ2VTdHJpbmdfKHBhdGgpLnJlcGxhY2UoL15cLysvLCAnJyk7CiAgY29uc3QgYmFzZSA9IGNsZWFuLnNwbGl0KCcvJykucG9wKCk7CiAgaWYgKGJhc2UgPT09ICdhcHBzc2NyaXB0Lmpzb24nKSB7CiAgICByZXR1cm4geyBuYW1lOiAnYXBwc3NjcmlwdCcsIHR5cGU6ICdKU09OJywgcGF0aDogY2xlYW4gfTsKICB9CiAgaWYgKC9cLmdzJC9pLnRlc3QoYmFzZSkpIHsKICAgIHJldHVybiB7IG5hbWU6IGJhc2UucmVwbGFjZSgvXC5ncyQvaSwgJycpLCB0eXBlOiAnU0VSVkVSX0pTJywgcGF0aDogY2xlYW4gfTsKICB9CiAgaWYgKC9cLmh0bWwkL2kudGVzdChiYXNlKSkgewogICAgcmV0dXJuIHsgbmFtZTogYmFzZS5yZXBsYWNlKC9cLmh0bWwkL2ksICcnKSwgdHlwZTogJ0hUTUwnLCBwYXRoOiBjbGVhbiB9OwogIH0KICByZXR1cm4gbnVsbDsKfQoKZnVuY3Rpb24gZm9yZ2VQdWxzZTA3OENhbm9uaWNhbFBhdGhfKHRhcmdldCwgZmlsZSkgewogIGlmIChmb3JnZVN0cmluZ18oZmlsZS5uYW1lKS50b0xvd2VyQ2FzZSgpID09PSAnYXBwc3NjcmlwdCcgJiYKICAgICAgZm9yZ2VTdHJpbmdfKGZpbGUudHlwZSkudG9VcHBlckNhc2UoKSA9PT0gJ0pTT04nKSB7CiAgICByZXR1cm4gdGFyZ2V0LmNvbnRyb2xsZXJQcm9qZWN0CiAgICAgID8gJ3B1bHNlLWZvcmdlL2FwcHNzY3JpcHQuanNvbicKICAgICAgOiB0YXJnZXQuY2Fub25pY2FsUm9vdC5yZXBsYWNlKC9cLyskLywgJycpICsgJy9hcHBzc2NyaXB0Lmpzb24nOwogIH0KCiAgY29uc3QgZXh0ZW5zaW9uID0gZm9yZ2VQdWxzZTA3OEV4dGVuc2lvbl8oZmlsZS50eXBlKTsKICBpZiAodGFyZ2V0LmNvbnRyb2xsZXJQcm9qZWN0KSB7CiAgICBjb25zdCBjb3JlTmFtZXMgPSB7CiAgICAgIEZvcmdlQ29yZTogdHJ1ZSwKICAgICAgRm9yZ2VSZWdpc3RyeTogdHJ1ZSwKICAgICAgRm9yZ2VWYWxpZGF0b3I6IHRydWUsCiAgICAgIEZvcmdlUHJvamVjdEFwaTogdHJ1ZSwKICAgICAgRm9yZ2VHaXRIdWI6IHRydWUsCiAgICAgIEZvcmdlRW5naW5lOiB0cnVlLAogICAgICBGb3JnZVJlY29uY2lsZTogdHJ1ZQogICAgfTsKICAgIGNvbnN0IGZvbGRlciA9IGNvcmVOYW1lc1tmaWxlLm5hbWVdID8gJ3B1bHNlLWZvcmdlL2NvcmUnIDogJ3B1bHNlLWZvcmdlL2NvbnRyb2xsZXInOwogICAgcmV0dXJuIGZvbGRlciArICcvJyArIGZpbGUubmFtZSArIGV4dGVuc2lvbjsKICB9CiAgcmV0dXJuIHRhcmdldC5jYW5vbmljYWxSb290LnJlcGxhY2UoL1wvKyQvLCAnJykgKyAnLycgKyBmaWxlLm5hbWUgKyBleHRlbnNpb247Cn0KCmZ1bmN0aW9uIGZvcmdlUHVsc2UwNzhTbmFwc2hvdFBhdGhfKGNhcHR1cmVJZCwgYWxpYXMsIGZpbGUpIHsKICBjb25zdCBzYWZlQWxpYXMgPSBmb3JnZVN0cmluZ18oYWxpYXMpLnJlcGxhY2UoL1teQS1aYS16MC05Xy1dL2csICdfJyk7CiAgY29uc3QgZXh0ZW5zaW9uID0gZm9yZ2VQdWxzZTA3OEV4dGVuc2lvbl8oZmlsZS50eXBlKTsKICBjb25zdCBuYW1lID0gZm9yZ2VTdHJpbmdfKGZpbGUubmFtZSkucmVwbGFjZSgvW15BLVphLXowLTlfLi1dL2csICdfJyk7CiAgcmV0dXJuICdwdWxzZS1mb3JnZS9yZWNvbmNpbGlhdGlvbi9QVUxTRS0wNzgvJyArCiAgICBjYXB0dXJlSWQgKyAnLycgKyBzYWZlQWxpYXMgKyAnL2xpdmUvJyArIG5hbWUgKyBleHRlbnNpb247Cn0KCmZ1bmN0aW9uIGZvcmdlUHVsc2UwNzhDb21wYXJlRmlsZXNfKGxpdmVGaWxlcywgcmVwb0ZpbGVzKSB7CiAgY29uc3QgbGl2ZSA9IGZvcmdlQ2Fub25pY2FsRmlsZXNfKGxpdmVGaWxlcyB8fCBbXSk7CiAgY29uc3QgcmVwbyA9IChyZXBvRmlsZXMgfHwgW10pLm1hcChmdW5jdGlvbihmaWxlKSB7CiAgICByZXR1cm4gewogICAgICBuYW1lOiBmb3JnZVN0cmluZ18oZmlsZS5uYW1lKSwKICAgICAgdHlwZTogZm9yZ2VTdHJpbmdfKGZpbGUudHlwZSkudG9VcHBlckNhc2UoKSwKICAgICAgc291cmNlOiBmb3JnZU5vcm1hbGl6ZVRleHRfKGZpbGUuc291cmNlKSwKICAgICAgcGF0aDogZm9yZ2VTdHJpbmdfKGZpbGUucGF0aCkKICAgIH07CiAgfSkuc29ydChmdW5jdGlvbihhLCBiKSB7CiAgICByZXR1cm4gZm9yZ2VQdWxzZTA3OEZpbGVJZGVudGl0eV8oYSkubG9jYWxlQ29tcGFyZShmb3JnZVB1bHNlMDc4RmlsZUlkZW50aXR5XyhiKSk7CiAgfSk7CgogIGNvbnN0IGxpdmVCeUtleSA9IHt9OwogIGNvbnN0IHJlcG9CeUtleSA9IHt9OwoKICBsaXZlLmZvckVhY2goZnVuY3Rpb24oZmlsZSkgewogICAgY29uc3Qga2V5ID0gZm9yZ2VQdWxzZTA3OEZpbGVJZGVudGl0eV8oZmlsZSk7CiAgICBmb3JnZUFzc2VydF8oIWxpdmVCeUtleVtrZXldLCAnRHVwbGljYXRlIGxpdmUgZmlsZSBpZGVudGl0eTogJyArIGtleSk7CiAgICBsaXZlQnlLZXlba2V5XSA9IGZpbGU7CiAgfSk7CiAgcmVwby5mb3JFYWNoKGZ1bmN0aW9uKGZpbGUpIHsKICAgIGNvbnN0IGtleSA9IGZvcmdlUHVsc2UwNzhGaWxlSWRlbnRpdHlfKGZpbGUpOwogICAgZm9yZ2VBc3NlcnRfKCFyZXBvQnlLZXlba2V5XSwgJ0R1cGxpY2F0ZSByZXBvc2l0b3J5IGZpbGUgaWRlbnRpdHk6ICcgKyBrZXkpOwogICAgcmVwb0J5S2V5W2tleV0gPSBmaWxlOwogIH0pOwoKICBjb25zdCBrZXlzID0gT2JqZWN0LmtleXMoT2JqZWN0LmFzc2lnbih7fSwgbGl2ZUJ5S2V5LCByZXBvQnlLZXkpKS5zb3J0KCk7CiAgcmV0dXJuIGtleXMubWFwKGZ1bmN0aW9uKGtleSkgewogICAgY29uc3QgbGl2ZUZpbGUgPSBsaXZlQnlLZXlba2V5XSB8fCBudWxsOwogICAgY29uc3QgcmVwb0ZpbGUgPSByZXBvQnlLZXlba2V5XSB8fCBudWxsOwogICAgY29uc3QgbGl2ZVNoYSA9IGxpdmVGaWxlID8gZm9yZ2VTaGEyNTZfKGxpdmVGaWxlLnNvdXJjZSkgOiAnJzsKICAgIGNvbnN0IHJlcG9TaGEgPSByZXBvRmlsZSA/IGZvcmdlU2hhMjU2XyhyZXBvRmlsZS5zb3VyY2UpIDogJyc7CiAgICBsZXQgc3RhdHVzID0gJ01BVENIJzsKICAgIGlmIChsaXZlRmlsZSAmJiAhcmVwb0ZpbGUpIHN0YXR1cyA9ICdMSVZFX09OTFknOwogICAgZWxzZSBpZiAoIWxpdmVGaWxlICYmIHJlcG9GaWxlKSBzdGF0dXMgPSAnUkVQT19PTkxZJzsKICAgIGVsc2UgaWYgKGxpdmVTaGEgIT09IHJlcG9TaGEpIHN0YXR1cyA9ICdESUZGJzsKCiAgICByZXR1cm4gewogICAgICBrZXk6IGtleSwKICAgICAgbmFtZTogKGxpdmVGaWxlIHx8IHJlcG9GaWxlKS5uYW1lLAogICAgICB0eXBlOiAobGl2ZUZpbGUgfHwgcmVwb0ZpbGUpLnR5cGUsCiAgICAgIHN0YXR1czogc3RhdHVzLAogICAgICBsaXZlU2hhMjU2OiBsaXZlU2hhLAogICAgICByZXBvU2hhMjU2OiByZXBvU2hhLAogICAgICByZXBvUGF0aDogcmVwb0ZpbGUgPyByZXBvRmlsZS5wYXRoIDogJycsCiAgICAgIGxpdmVCeXRlczogbGl2ZUZpbGUgPyBmb3JnZVV0ZjhCeXRlc18obGl2ZUZpbGUuc291cmNlKSA6IDAsCiAgICAgIHJlcG9CeXRlczogcmVwb0ZpbGUgPyBmb3JnZVV0ZjhCeXRlc18ocmVwb0ZpbGUuc291cmNlKSA6IDAKICAgIH07CiAgfSk7Cn0KCmZ1bmN0aW9uIGZvcmdlUHVsc2UwNzhSZXBvVHJlZV8ocmVmKSB7CiAgY29uc3QgYnJhbmNoID0gZm9yZ2VTdHJpbmdfKHJlZiB8fCAnbWFpbicpOwogIGNvbnN0IHRyZWUgPSBmb3JnZUdpdEh1YkFwaV8oCiAgICAnL2dpdC90cmVlcy8nICsgZW5jb2RlVVJJQ29tcG9uZW50KGJyYW5jaCkgKyAnP3JlY3Vyc2l2ZT0xJywKICAgIHsgbWV0aG9kOiAnZ2V0JyB9CiAgKTsKICBmb3JnZUFzc2VydF8odHJlZSAmJiBBcnJheS5pc0FycmF5KHRyZWUudHJlZSksICdHaXRIdWIgcmVwb3NpdG9yeSB0cmVlIHdhcyBub3QgcmV0dXJuZWQuJyk7CiAgZm9yZ2VBc3NlcnRfKHRyZWUudHJ1bmNhdGVkICE9PSB0cnVlLCAnR2l0SHViIHJlcG9zaXRvcnkgdHJlZSB3YXMgdHJ1bmNhdGVkOyByZWNvbmNpbGlhdGlvbiBzdG9wcGVkLicpOwogIHJldHVybiB0cmVlLnRyZWU7Cn0KCmZ1bmN0aW9uIGZvcmdlUHVsc2UwNzhQYXRoSW5jbHVkZWRfKHRhcmdldCwgcGF0aCkgewogIGNvbnN0IGNsZWFuID0gZm9yZ2VTdHJpbmdfKHBhdGgpOwogIGlmICgodGFyZ2V0LnJlcG9FeGFjdCB8fCBbXSkuaW5kZXhPZihjbGVhbikgPj0gMCkgcmV0dXJuIHRydWU7CiAgcmV0dXJuICh0YXJnZXQucmVwb1Jvb3RzIHx8IFtdKS5zb21lKGZ1bmN0aW9uKHJvb3QpIHsKICAgIHJldHVybiBjbGVhbi5pbmRleE9mKHJvb3QpID09PSAwOwogIH0pOwp9CgpmdW5jdGlvbiBmb3JnZVB1bHNlMDc4UmVhZFJlcG9UZXh0XyhwYXRoLCByZWYpIHsKICBjb25zdCBlbmNvZGVkID0gZm9yZ2VTdHJpbmdfKHBhdGgpLnNwbGl0KCcvJykubWFwKGVuY29kZVVSSUNvbXBvbmVudCkuam9pbignLycpOwogIGNvbnN0IHJlc3VsdCA9IGZvcmdlR2l0SHViQXBpXygKICAgICcvY29udGVudHMvJyArIGVuY29kZWQgKyAnP3JlZj0nICsgZW5jb2RlVVJJQ29tcG9uZW50KHJlZiB8fCAnbWFpbicpLAogICAgeyBtZXRob2Q6ICdnZXQnIH0KICApOwogIGZvcmdlQXNzZXJ0XygKICAgIHJlc3VsdCAmJiByZXN1bHQuZW5jb2RpbmcgPT09ICdiYXNlNjQnICYmIHJlc3VsdC5jb250ZW50LAogICAgJ0dpdEh1YiBzb3VyY2Ugd2FzIG5vdCByZXR1cm5lZCBmb3IgJyArIHBhdGgKICApOwogIGNvbnN0IGNvbXBhY3QgPSBmb3JnZVN0cmluZ18ocmVzdWx0LmNvbnRlbnQpLnJlcGxhY2UoL1xzL2csICcnKTsKICByZXR1cm4gVXRpbGl0aWVzLm5ld0Jsb2IoVXRpbGl0aWVzLmJhc2U2NERlY29kZShjb21wYWN0KSkuZ2V0RGF0YUFzU3RyaW5nKCdVVEYtOCcpOwp9CgpmdW5jdGlvbiBmb3JnZVB1bHNlMDc4UmVwb0ZpbGVzRm9yVGFyZ2V0Xyh0YXJnZXQsIHRyZWUsIHJlZikgewogIGNvbnN0IGZpbGVzID0gW107CiAgKHRyZWUgfHwgW10pLmZvckVhY2goZnVuY3Rpb24oZW50cnkpIHsKICAgIGlmICghZW50cnkgfHwgZW50cnkudHlwZSAhPT0gJ2Jsb2InKSByZXR1cm47CiAgICBpZiAoIWZvcmdlUHVsc2UwNzhQYXRoSW5jbHVkZWRfKHRhcmdldCwgZW50cnkucGF0aCkpIHJldHVybjsKICAgIGNvbnN0IGlkZW50aXR5ID0gZm9yZ2VQdWxzZTA3OFJlcG9JZGVudGl0eUZyb21QYXRoXyhlbnRyeS5wYXRoKTsKICAgIGlmICghaWRlbnRpdHkpIHJldHVybjsKICAgIGZpbGVzLnB1c2goewogICAgICBuYW1lOiBpZGVudGl0eS5uYW1lLAogICAgICB0eXBlOiBpZGVudGl0eS50eXBlLAogICAgICBwYXRoOiBpZGVudGl0eS5wYXRoLAogICAgICBzb3VyY2U6IGZvcmdlUHVsc2UwNzhSZWFkUmVwb1RleHRfKGlkZW50aXR5LnBhdGgsIHJlZikKICAgIH0pOwogIH0pOwoKICBjb25zdCBzZWVuID0ge307CiAgZmlsZXMuZm9yRWFjaChmdW5jdGlvbihmaWxlKSB7CiAgICBjb25zdCBrZXkgPSBmb3JnZVB1bHNlMDc4RmlsZUlkZW50aXR5XyhmaWxlKTsKICAgIGZvcmdlQXNzZXJ0Xyghc2VlbltrZXldLCAnUmVwb3NpdG9yeSBtYXBzIG11bHRpcGxlIGZpbGVzIHRvIEFwcHMgU2NyaXB0IGlkZW50aXR5ICcgKyBrZXkpOwogICAgc2VlbltrZXldID0gdHJ1ZTsKICB9KTsKICByZXR1cm4gZmlsZXM7Cn0KCmZ1bmN0aW9uIGZvcmdlUHVsc2UwNzhMaXZlRmlsZU1hcF8oZmlsZXMpIHsKICBjb25zdCBtYXAgPSB7fTsKICBmb3JnZUNhbm9uaWNhbEZpbGVzXyhmaWxlcyB8fCBbXSkuZm9yRWFjaChmdW5jdGlvbihmaWxlKSB7CiAgICBtYXBbZm9yZ2VQdWxzZTA3OEZpbGVJZGVudGl0eV8oZmlsZSldID0gZmlsZTsKICB9KTsKICByZXR1cm4gbWFwOwp9CgpmdW5jdGlvbiBmb3JnZVB1bHNlMDc4UmVwb0ZpbGVNYXBfKGZpbGVzKSB7CiAgY29uc3QgbWFwID0ge307CiAgKGZpbGVzIHx8IFtdKS5mb3JFYWNoKGZ1bmN0aW9uKGZpbGUpIHsKICAgIG1hcFtmb3JnZVB1bHNlMDc4RmlsZUlkZW50aXR5XyhmaWxlKV0gPSBmaWxlOwogIH0pOwogIHJldHVybiBtYXA7Cn0KCmZ1bmN0aW9uIGZvcmdlUHVsc2UwNzhBY3Rpb25Gb3JfKHRhcmdldCwgY29tcGFyaXNvbikgewogIGlmIChjb21wYXJpc29uLnN0YXR1cyA9PT0gJ01BVENIJykgcmV0dXJuICdOT19DSEFOR0UnOwogIGlmIChjb21wYXJpc29uLnN0YXR1cyA9PT0gJ1JFUE9fT05MWScpIHJldHVybiAnS0VFUF9SRVBPJzsKICBpZiAodGFyZ2V0LmF1dGhvcml0eSA9PT0gJ1JFUE8nICYmIGNvbXBhcmlzb24uc3RhdHVzID09PSAnRElGRicpIHsKICAgIHJldHVybiAnUkVWSUVXX1JFUE9fUFJFRkVSUkVEJzsKICB9CiAgaWYgKGNvbXBhcmlzb24uc3RhdHVzID09PSAnTElWRV9PTkxZJyAmJiB0YXJnZXQuaW1wb3J0TGl2ZU9ubHkgIT09IHRydWUpIHsKICAgIHJldHVybiAnU05BUFNIT1RfT05MWSc7CiAgfQogIHJldHVybiAnUFJPUE9TRV9MSVZFX1RPX0NBTk9OSUNBTCc7Cn0KCmZ1bmN0aW9uIGZvcmdlUHVsc2UwNzhQdXRQckZpbGVfKGZpbGVNYXAsIHBhdGgsIGNvbnRlbnQpIHsKICBjb25zdCBjbGVhbiA9IGZvcmdlU3RyaW5nXyhwYXRoKS5yZXBsYWNlKC9eXC8rLywgJycpOwogIGZvcmdlQXNzZXJ0XyhjbGVhbiwgJ1BSIGZpbGUgcGF0aCBpcyByZXF1aXJlZC4nKTsKICBjb25zdCBub3JtYWxpemVkID0gZm9yZ2VOb3JtYWxpemVUZXh0Xyhjb250ZW50KTsKICBpZiAoT2JqZWN0LnByb3RvdHlwZS5oYXNPd25Qcm9wZXJ0eS5jYWxsKGZpbGVNYXAsIGNsZWFuKSkgewogICAgZm9yZ2VBc3NlcnRfKGZpbGVNYXBbY2xlYW5dID09PSBub3JtYWxpemVkLCAnQ29uZmxpY3RpbmcgZ2VuZXJhdGVkIFBSIGNvbnRlbnQgZm9yICcgKyBjbGVhbik7CiAgICByZXR1cm47CiAgfQogIGZpbGVNYXBbY2xlYW5dID0gbm9ybWFsaXplZDsKfQoKZnVuY3Rpb24gZm9yZ2VQdWxzZTA3OFJ1blNvdXJjZVJlY29uY2lsaWF0aW9uKCkgewogIHJldHVybiBmb3JnZVdpdGhCdWlsZExvY2tfKGZ1bmN0aW9uKCkgewogICAgY29uc3QgdGFyZ2V0cyA9IGZvcmdlUHVsc2UwNzhUYXJnZXRzXygpOwogICAgY29uc3Qgd3JpdGVyQm91bmRhcnkgPSBmb3JnZVB1bHNlMDc4QXNzZXJ0V3JpdGVyQm91bmRhcnlfKHRhcmdldHMpOwogICAgY29uc3QgcmVmID0gJ21haW4nOwogICAgY29uc3QgdHJlZSA9IGZvcmdlUHVsc2UwNzhSZXBvVHJlZV8ocmVmKTsKICAgIGNvbnN0IGNhcHR1cmVJZCA9IFV0aWxpdGllcy5mb3JtYXREYXRlKAogICAgICBuZXcgRGF0ZSgpLAogICAgICBTZXNzaW9uLmdldFNjcmlwdFRpbWVab25lKCkgfHwgJ0FtZXJpY2EvTmV3X1lvcmsnLAogICAgICAneXl5eU1NZGQtSEhtbXNzJwogICAgKTsKCiAgICBjb25zdCBwckZpbGVzID0ge307CiAgICBjb25zdCB0YXJnZXRSZXBvcnRzID0gW107CiAgICBsZXQgcHJvcG9zZWRDYW5vbmljYWxDaGFuZ2VzID0gMDsKCiAgICB0YXJnZXRzLmZvckVhY2goZnVuY3Rpb24odGFyZ2V0KSB7CiAgICAgIGNvbnN0IGxpdmUgPSBmb3JnZUdldFNjcmlwdENvbnRlbnQodGFyZ2V0LnNjcmlwdElkKTsKICAgICAgY29uc3QgcmVwb0ZpbGVzID0gZm9yZ2VQdWxzZTA3OFJlcG9GaWxlc0ZvclRhcmdldF8odGFyZ2V0LCB0cmVlLCByZWYpOwogICAgICBjb25zdCBjb21wYXJpc29ucyA9IGZvcmdlUHVsc2UwNzhDb21wYXJlRmlsZXNfKGxpdmUuZmlsZXMsIHJlcG9GaWxlcyk7CiAgICAgIGNvbnN0IGxpdmVNYXAgPSBmb3JnZVB1bHNlMDc4TGl2ZUZpbGVNYXBfKGxpdmUuZmlsZXMpOwogICAgICBjb25zdCByZXBvTWFwID0gZm9yZ2VQdWxzZTA3OFJlcG9GaWxlTWFwXyhyZXBvRmlsZXMpOwoKICAgICAgbGl2ZS5maWxlcy5mb3JFYWNoKGZ1bmN0aW9uKGZpbGUpIHsKICAgICAgICBmb3JnZVB1bHNlMDc4UHV0UHJGaWxlXygKICAgICAgICAgIHByRmlsZXMsCiAgICAgICAgICBmb3JnZVB1bHNlMDc4U25hcHNob3RQYXRoXyhjYXB0dXJlSWQsIHRhcmdldC5hbGlhcywgZmlsZSksCiAgICAgICAgICBmaWxlLnNvdXJjZQogICAgICAgICk7CiAgICAgIH0pOwoKICAgICAgY29uc3QgZmlsZVJlcG9ydHMgPSBjb21wYXJpc29ucy5tYXAoZnVuY3Rpb24oY29tcGFyaXNvbikgewogICAgICAgIGNvbnN0IGFjdGlvbiA9IGZvcmdlUHVsc2UwNzhBY3Rpb25Gb3JfKHRhcmdldCwgY29tcGFyaXNvbik7CiAgICAgICAgY29uc3QgbGl2ZUZpbGUgPSBsaXZlTWFwW2NvbXBhcmlzb24ua2V5XSB8fCBudWxsOwogICAgICAgIGNvbnN0IHJlcG9GaWxlID0gcmVwb01hcFtjb21wYXJpc29uLmtleV0gfHwgbnVsbDsKICAgICAgICBsZXQgY2Fub25pY2FsUGF0aCA9IHJlcG9GaWxlID8gcmVwb0ZpbGUucGF0aCA6ICcnOwoKICAgICAgICBpZiAoYWN0aW9uID09PSAnUFJPUE9TRV9MSVZFX1RPX0NBTk9OSUNBTCcpIHsKICAgICAgICAgIGZvcmdlQXNzZXJ0XyhsaXZlRmlsZSwgJ0xpdmUgc291cmNlIGlzIHJlcXVpcmVkIGZvciBjYW5vbmljYWwgaW1wb3J0LicpOwogICAgICAgICAgY2Fub25pY2FsUGF0aCA9IGNhbm9uaWNhbFBhdGggfHwgZm9yZ2VQdWxzZTA3OENhbm9uaWNhbFBhdGhfKHRhcmdldCwgbGl2ZUZpbGUpOwogICAgICAgICAgZm9yZ2VQdWxzZTA3OFB1dFByRmlsZV8ocHJGaWxlcywgY2Fub25pY2FsUGF0aCwgbGl2ZUZpbGUuc291cmNlKTsKICAgICAgICAgIHByb3Bvc2VkQ2Fub25pY2FsQ2hhbmdlcyArPSAxOwogICAgICAgIH0KCiAgICAgICAgcmV0dXJuIE9iamVjdC5hc3NpZ24oe30sIGNvbXBhcmlzb24sIHsKICAgICAgICAgIGFjdGlvbjogYWN0aW9uLAogICAgICAgICAgY2Fub25pY2FsUGF0aDogY2Fub25pY2FsUGF0aAogICAgICAgIH0pOwogICAgICB9KTsKCiAgICAgIGNvbnN0IGludmVudG9yeSA9IHsKICAgICAgICB0YXNrSWQ6IEZPUkdFX1BVTFNFMDc4X1RBU0tfSURfLAogICAgICAgIGNhcHR1cmVJZDogY2FwdHVyZUlkLAogICAgICAgIGFsaWFzOiB0YXJnZXQuYWxpYXMsCiAgICAgICAgc2NyaXB0SWQ6IHRhcmdldC5zY3JpcHRJZCwKICAgICAgICBhdXRob3JpdHk6IHRhcmdldC5hdXRob3JpdHksCiAgICAgICAgcmlkZVJlcXVlc3RzV3JpdGVyOiB0YXJnZXQucmlkZVJlcXVlc3RzV3JpdGVyID09PSB0cnVlLAogICAgICAgIGxpdmVQYWNrYWdlSGFzaDogbGl2ZS5wYWNrYWdlSGFzaCwKICAgICAgICBsaXZlSW52ZW50b3J5OiBsaXZlLmludmVudG9yeSwKICAgICAgICByZXBvc2l0b3J5RmlsZXM6IHJlcG9GaWxlcy5tYXAoZnVuY3Rpb24oZmlsZSkgewogICAgICAgICAgcmV0dXJuIHsKICAgICAgICAgICAgcGF0aDogZmlsZS5wYXRoLAogICAgICAgICAgICBuYW1lOiBmaWxlLm5hbWUsCiAgICAgICAgICAgIHR5cGU6IGZpbGUudHlwZSwKICAgICAgICAgICAgYnl0ZXM6IGZvcmdlVXRmOEJ5dGVzXyhmaWxlLnNvdXJjZSksCiAgICAgICAgICAgIHNoYTI1NjogZm9yZ2VTaGEyNTZfKGZpbGUuc291cmNlKQogICAgICAgICAgfTsKICAgICAgICB9KSwKICAgICAgICBmaWxlczogZmlsZVJlcG9ydHMsCiAgICAgICAgcHJvZHVjdGlvblByb2plY3RNdXRhdGVkOiBmYWxzZQogICAgICB9OwogICAgICBjb25zdCBpbnZlbnRvcnlQYXRoID0gJ3B1bHNlLWZvcmdlL3JlY29uY2lsaWF0aW9uL1BVTFNFLTA3OC8nICsKICAgICAgICBjYXB0dXJlSWQgKyAnLycgKyB0YXJnZXQuYWxpYXMgKyAnL2ludmVudG9yeS5qc29uJzsKICAgICAgZm9yZ2VQdWxzZTA3OFB1dFByRmlsZV8ocHJGaWxlcywgaW52ZW50b3J5UGF0aCwgSlNPTi5zdHJpbmdpZnkoaW52ZW50b3J5LCBudWxsLCAyKSArICdcbicpOwoKICAgICAgdGFyZ2V0UmVwb3J0cy5wdXNoKGludmVudG9yeSk7CiAgICB9KTsKCiAgICBjb25zdCBjb3VudHMgPSB7IE1BVENIOiAwLCBESUZGOiAwLCBMSVZFX09OTFk6IDAsIFJFUE9fT05MWTogMCB9OwogICAgdGFyZ2V0UmVwb3J0cy5mb3JFYWNoKGZ1bmN0aW9uKHRhcmdldCkgewogICAgICB0YXJnZXQuZmlsZXMuZm9yRWFjaChmdW5jdGlvbihmaWxlKSB7CiAgICAgICAgY291bnRzW2ZpbGUuc3RhdHVzXSArPSAxOwogICAgICB9KTsKICAgIH0pOwoKICAgIGNvbnN0IHJlcG9ydCA9IHsKICAgICAgdGFza0lkOiBGT1JHRV9QVUxTRTA3OF9UQVNLX0lEXywKICAgICAgY2FwdHVyZUlkOiBjYXB0dXJlSWQsCiAgICAgIGNhcHR1cmVkQXQ6IGZvcmdlTm93SXNvXygpLAogICAgICByZXBvc2l0b3J5OiBmb3JnZUdpdEh1YlJlcG9zaXRvcnlfKCksCiAgICAgIHJlcG9zaXRvcnlSZWY6IHJlZiwKICAgICAgd3JpdGVyQm91bmRhcnk6IHdyaXRlckJvdW5kYXJ5LAogICAgICB0YXJnZXRzOiB0YXJnZXRSZXBvcnRzLAogICAgICBjb3VudHM6IGNvdW50cywKICAgICAgcHJvcG9zZWRDYW5vbmljYWxDaGFuZ2VzOiBwcm9wb3NlZENhbm9uaWNhbENoYW5nZXMsCiAgICAgIGFwcHNTY3JpcHRIZWFkV3JpdGVzOiAwLAogICAgICBkZXBsb3ltZW50c0NyZWF0ZWQ6IDAsCiAgICAgIGVuZ2luZUFjdGl2YXRpb25zOiAwLAogICAgICBwcm9kdWN0aW9uRGF0YUNoYW5nZWQ6IGZhbHNlLAogICAgICBhdXRvbWF0aWNNZXJnZTogZmFsc2UsCiAgICAgIHByb2R1Y3Rpb25Ub3VjaGVkOiBmYWxzZQogICAgfTsKICAgIHJlcG9ydC5yZXBvcnRIYXNoID0gZm9yZ2VTaGEyNTZfKGZvcmdlU3RhYmxlSnNvbl8ocmVwb3J0KSk7CgogICAgY29uc3QgYmFzZVBhdGggPSAncHVsc2UtZm9yZ2UvcmVjb25jaWxpYXRpb24vUFVMU0UtMDc4LycgKyBjYXB0dXJlSWQ7CiAgICBmb3JnZVB1bHNlMDc4UHV0UHJGaWxlXygKICAgICAgcHJGaWxlcywKICAgICAgYmFzZVBhdGggKyAnL3JlcG9ydC5qc29uJywKICAgICAgSlNPTi5zdHJpbmdpZnkocmVwb3J0LCBudWxsLCAyKSArICdcbicKICAgICk7CiAgICBmb3JnZVB1bHNlMDc4UHV0UHJGaWxlXygKICAgICAgcHJGaWxlcywKICAgICAgYmFzZVBhdGggKyAnL1JFQURNRS5tZCcsCiAgICAgIFsKICAgICAgICAnIyBQVUxTRS0wNzggbGl2ZS1zb3VyY2UgcmVjb25jaWxpYXRpb24nLAogICAgICAgICcnLAogICAgICAgICctIENhcHR1cmU6IGAnICsgY2FwdHVyZUlkICsgJ2AnLAogICAgICAgICctIFJlcG9ydCBoYXNoOiBgJyArIHJlcG9ydC5yZXBvcnRIYXNoICsgJ2AnLAogICAgICAgICctIE1BVENIOiAnICsgY291bnRzLk1BVENILAogICAgICAgICctIERJRkY6ICcgKyBjb3VudHMuRElGRiwKICAgICAgICAnLSBMSVZFX09OTFk6ICcgKyBjb3VudHMuTElWRV9PTkxZLAogICAgICAgICctIFJFUE9fT05MWTogJyArIGNvdW50cy5SRVBPX09OTFksCiAgICAgICAgJy0gUHJvcG9zZWQgY2Fub25pY2FsIGNoYW5nZXM6ICcgKyBwcm9wb3NlZENhbm9uaWNhbENoYW5nZXMsCiAgICAgICAgJy0gQXV0aG9yaXplZCBSaWRlIFJlcXVlc3RzIHdyaXRlcjogYFBVTFNFX1JFUVVFU1RfQVBQYCcsCiAgICAgICAgJy0gQXBwcyBTY3JpcHQgSEVBRCB3cml0ZXM6IDAnLAogICAgICAgICctIERlcGxveW1lbnRzOiAwJywKICAgICAgICAnLSBQcm9kdWN0aW9uIGRhdGEgY2hhbmdlczogbm9uZScsCiAgICAgICAgJycsCiAgICAgICAgJ0NvbnRyb2xsZXIgZHJpZnQgcmVtYWlucyByZXBvc2l0b3J5LXByZWZlcnJlZC4gTGl2ZSBhcHBsaWNhdGlvbiBkcmlmdCBpcyBwcm9wb3NlZCcsCiAgICAgICAgJ3Rocm91Z2ggdGhpcyByZXZpZXdlZCBQUi4gRXZlcnkgY29tcGxldGUgbGl2ZSBzb3VyY2UgZmlsZSBpcyBhbHNvIHByZXNlcnZlZCB1bmRlcicsCiAgICAgICAgJ3RoZSBjYXB0dXJlIGZvbGRlciBiZWZvcmUgYW55IGNhbm9uaWNhbCBzb3VyY2UgY2hhbmdlIGlzIHJldmlld2VkLicsCiAgICAgICAgJycKICAgICAgXS5qb2luKCdcbicpCiAgICApOwoKICAgIGNvbnN0IHN0YW1wID0gY2FwdHVyZUlkOwogICAgY29uc3QgcHVsbCA9IGZvcmdlR2l0SHViQ3JlYXRlUHVsbFJlcXVlc3QoewogICAgICBiYXNlQnJhbmNoOiAnbWFpbicsCiAgICAgIGhlYWRCcmFuY2g6ICdwdWxzZS9wdWxzZS0wNzgtc291cmNlLXJlY29uY2lsaWF0aW9uLScgKyBzdGFtcCwKICAgICAgdGl0bGU6ICdQVUxTRS0wNzg6IFJlY29uY2lsZSBsaXZlIFB1bHNlIEFwcHMgU2NyaXB0IHNvdXJjZScsCiAgICAgIGNvbW1pdE1lc3NhZ2U6ICdDYXB0dXJlIGFuZCByZWNvbmNpbGUgbGl2ZSBQdWxzZSBBcHBzIFNjcmlwdCBzb3VyY2UnLAogICAgICBib2R5OiBbCiAgICAgICAgJyMjIFBVTFNFLTA3OCBzb3VyY2UgcmVjb25jaWxpYXRpb24nLAogICAgICAgICcnLAogICAgICAgICdSZWFkcyBjb21wbGV0ZSBsaXZlIHNvdXJjZSBmb3IgdGhlIEZvcmdlIGNvbnRyb2xsZXIsIEhveSBEcml2ZXIsIHN0YW5kYWxvbmUnLAogICAgICAgICdyZXF1ZXN0IGFwcCwgYW5kIFJ1bnRpbWUgTGl0ZS9yaWRlci1zdGF0dXMgcHJvamVjdC4nLAogICAgICAgICcnLAogICAgICAgICcjIyMgRXZpZGVuY2UnLAogICAgICAgICctIEltbXV0YWJsZSBsaXZlIHNvdXJjZSBzbmFwc2hvdHMgYW5kIFNIQS0yNTYgaW52ZW50b3JpZXMnLAogICAgICAgICctIFBlci1maWxlIE1BVENIIC8gRElGRiAvIExJVkVfT05MWSAvIFJFUE9fT05MWSBjbGFzc2lmaWNhdGlvbicsCiAgICAgICAgJy0gUmVwb3NpdG9yeS1wcmVmZXJyZWQgY29udHJvbGxlciBkcmlmdCBoYW5kbGluZycsCiAgICAgICAgJy0gTGl2ZS1wcmVmZXJyZWQgYXBwbGljYXRpb24gZHJpZnQgcHJvcG9zZWQgdGhyb3VnaCByZXZpZXcnLAogICAgICAgICctIFN0YW5kYWxvbmUgcmVxdWVzdCBhcHAgcmVtYWlucyB0aGUgb25seSBkZWNsYXJlZCBSaWRlIFJlcXVlc3RzIHdyaXRlcicsCiAgICAgICAgJycsCiAgICAgICAgJyMjIyBTYWZldHknLAogICAgICAgICctIE5vIEFwcHMgU2NyaXB0IEhFQUQgd3JpdGVzJywKICAgICAgICAnLSBObyBkZXBsb3ltZW50cycsCiAgICAgICAgJy0gTm8gZW5naW5lIGFjdGl2YXRpb24nLAogICAgICAgICctIE5vIGF1dG9tYXRpYyBtZXJnZScsCiAgICAgICAgJy0gTm8gcHJvZHVjdGlvbiBkYXRhIG11dGF0aW9uJywKICAgICAgICAnJywKICAgICAgICAnUmVwb3J0IGhhc2g6IGAnICsgcmVwb3J0LnJlcG9ydEhhc2ggKyAnYCcKICAgICAgXS5qb2luKCdcbicpLAogICAgICBmaWxlczogT2JqZWN0LmtleXMocHJGaWxlcykuc29ydCgpLm1hcChmdW5jdGlvbihwYXRoKSB7CiAgICAgICAgcmV0dXJuIHsgcGF0aDogcGF0aCwgY29udGVudDogcHJGaWxlc1twYXRoXSB9OwogICAgICB9KQogICAgfSk7CgogICAgY29uc3QgcmVjZWlwdElkZW50aXR5ID0gewogICAgICB0YXNrSWQ6IEZPUkdFX1BVTFNFMDc4X1RBU0tfSURfLAogICAgICBjYXB0dXJlSWQ6IGNhcHR1cmVJZCwKICAgICAgcmVwb3J0SGFzaDogcmVwb3J0LnJlcG9ydEhhc2gsCiAgICAgIGNvbW1pdFNoYTogcHVsbC5jb21taXRTaGEsCiAgICAgIHB1bGxSZXF1ZXN0TnVtYmVyOiBwdWxsLnB1bGxSZXF1ZXN0Lm51bWJlcgogICAgfTsKICAgIGNvbnN0IHJlY2VpcHRJZCA9IGZvcmdlU2hhMjU2Xyhmb3JnZVN0YWJsZUpzb25fKHJlY2VpcHRJZGVudGl0eSkpOwogICAgY29uc3QgcmVjZWlwdCA9IE9iamVjdC5hc3NpZ24oe30sIHJlY2VpcHRJZGVudGl0eSwgewogICAgICByZWNlaXB0SWQ6IHJlY2VpcHRJZCwKICAgICAgb2s6IHRydWUsCiAgICAgIHB1bGxSZXF1ZXN0VXJsOiBwdWxsLnB1bGxSZXF1ZXN0LnVybCwKICAgICAgY291bnRzOiBjb3VudHMsCiAgICAgIHByb3Bvc2VkQ2Fub25pY2FsQ2hhbmdlczogcHJvcG9zZWRDYW5vbmljYWxDaGFuZ2VzLAogICAgICB3cml0ZXJCb3VuZGFyeTogd3JpdGVyQm91bmRhcnksCiAgICAgIGFwcHNTY3JpcHRIZWFkV3JpdGVzOiAwLAogICAgICBwcm9kdWN0aW9uVG91Y2hlZDogZmFsc2UsCiAgICAgIGF1dG9tYXRpY01lcmdlOiBmYWxzZSwKICAgICAgY3JlYXRlZEF0OiBmb3JnZU5vd0lzb18oKQogICAgfSk7CgogICAgY29uc3QgcHJvcHMgPSBQcm9wZXJ0aWVzU2VydmljZS5nZXRTY3JpcHRQcm9wZXJ0aWVzKCk7CiAgICBwcm9wcy5zZXRQcm9wZXJ0eShGT1JHRV9QVUxTRTA3OF9SRUNFSVBUX1BSRUZJWF8gKyByZWNlaXB0SWQsIGZvcmdlU3RhYmxlSnNvbl8ocmVjZWlwdCkpOwogICAgcHJvcHMuc2V0UHJvcGVydHkoRk9SR0VfUFVMU0UwNzhfTEFURVNUX1JFQ0VJUFRfS0VZXywgcmVjZWlwdElkKTsKCiAgICBjb25zb2xlLmxvZyhKU09OLnN0cmluZ2lmeShyZWNlaXB0LCBudWxsLCAyKSk7CiAgICByZXR1cm4gcmVjZWlwdDsKICB9KTsKfQoKZnVuY3Rpb24gZm9yZ2VQdWxzZTA3OFNlbGZUZXN0KCkgewogIGNvbnN0IGxpdmUgPSBbCiAgICB7IG5hbWU6ICdBJywgdHlwZTogJ1NFUlZFUl9KUycsIHNvdXJjZTogJ3NhbWUnIH0sCiAgICB7IG5hbWU6ICdCJywgdHlwZTogJ0hUTUwnLCBzb3VyY2U6ICdsaXZlLWRpZmYnIH0sCiAgICB7IG5hbWU6ICdDJywgdHlwZTogJ1NFUlZFUl9KUycsIHNvdXJjZTogJ2xpdmUtb25seScgfQogIF07CiAgY29uc3QgcmVwbyA9IFsKICAgIHsgbmFtZTogJ0EnLCB0eXBlOiAnU0VSVkVSX0pTJywgc291cmNlOiAnc2FtZScsIHBhdGg6ICdBLmdzJyB9LAogICAgeyBuYW1lOiAnQicsIHR5cGU6ICdIVE1MJywgc291cmNlOiAncmVwby1kaWZmJywgcGF0aDogJ0IuaHRtbCcgfSwKICAgIHsgbmFtZTogJ0QnLCB0eXBlOiAnSlNPTicsIHNvdXJjZTogJ3t9JywgcGF0aDogJ0QuanNvbicgfQogIF07CiAgY29uc3Qgc3RhdHVzZXMgPSBmb3JnZVB1bHNlMDc4Q29tcGFyZUZpbGVzXyhsaXZlLCByZXBvKS5tYXAoZnVuY3Rpb24oaXRlbSkgewogICAgcmV0dXJuIGl0ZW0uc3RhdHVzOwogIH0pLnNvcnQoKTsKCiAgY29uc3QgYm91bmRhcnkgPSBmb3JnZVB1bHNlMDc4QXNzZXJ0V3JpdGVyQm91bmRhcnlfKFsKICAgIHsgYWxpYXM6ICdQVUxTRV9SRVFVRVNUX0FQUCcsIHJpZGVSZXF1ZXN0c1dyaXRlcjogdHJ1ZSB9LAogICAgeyBhbGlhczogJ0hPWV9EUklWRVInLCByaWRlUmVxdWVzdHNXcml0ZXI6IGZhbHNlIH0KICBdKTsKCiAgcmV0dXJuIHsKICAgIG9rOiBmb3JnZVN0YWJsZUpzb25fKHN0YXR1c2VzKSA9PT0gZm9yZ2VTdGFibGVKc29uXyhbJ0RJRkYnLCAnTElWRV9PTkxZJywgJ01BVENIJywgJ1JFUE9fT05MWSddKSAmJgogICAgICBib3VuZGFyeS5vayA9PT0gdHJ1ZSAmJgogICAgICBmb3JnZVB1bHNlMDc4Q2Fub25pY2FsUGF0aF8oCiAgICAgICAgeyBjb250cm9sbGVyUHJvamVjdDogZmFsc2UsIGNhbm9uaWNhbFJvb3Q6ICdleGFtcGxlJyB9LAogICAgICAgIHsgbmFtZTogJ0NvZGUnLCB0eXBlOiAnU0VSVkVSX0pTJyB9CiAgICAgICkgPT09ICdleGFtcGxlL0NvZGUuZ3MnLAogICAgc3RhdHVzZXM6IHN0YXR1c2VzLAogICAgd3JpdGVyQm91bmRhcnk6IGJvdW5kYXJ5LAogICAgd3JpdGVzUGVyZm9ybWVkOiBmYWxzZSwKICAgIHByb2R1Y3Rpb25Ub3VjaGVkOiBmYWxzZQogIH07Cn0K')
      },
      {
        path: testPath,
        content: forgePulse078InstallerDecode_('aW1wb3J0IGZzIGZyb20gJ25vZGU6ZnMnOwppbXBvcnQgcGF0aCBmcm9tICdub2RlOnBhdGgnOwppbXBvcnQgdm0gZnJvbSAnbm9kZTp2bSc7CmltcG9ydCBjcnlwdG8gZnJvbSAnbm9kZTpjcnlwdG8nOwoKY29uc3QgY3dkID0gcHJvY2Vzcy5jd2QoKTsKY29uc3Qgcm9vdCA9IHBhdGguYmFzZW5hbWUoY3dkKSA9PT0gJ3B1bHNlLWZvcmdlJwogID8gY3dkCiAgOiBwYXRoLnJlc29sdmUoY3dkLCAncHVsc2UtZm9yZ2UnKTsKY29uc3Qgc291cmNlUGF0aCA9IHBhdGguam9pbihyb290LCAnY29udHJvbGxlci9QVUxTRTA3OFNvdXJjZVJlY29uY2lsaWF0aW9uLmdzJyk7CmNvbnN0IHByb2JsZW1zID0gW107CgpsZXQgc291cmNlID0gJyc7CmlmICghZnMuZXhpc3RzU3luYyhzb3VyY2VQYXRoKSkgewogIHByb2JsZW1zLnB1c2goYE1pc3NpbmcgUFVMU0UtMDc4IGZpbGU6ICR7c291cmNlUGF0aH1gKTsKfSBlbHNlIHsKICBzb3VyY2UgPSBmcy5yZWFkRmlsZVN5bmMoc291cmNlUGF0aCwgJ3V0ZjgnKTsKICB0cnkgewogICAgbmV3IHZtLlNjcmlwdChzb3VyY2UsIHsgZmlsZW5hbWU6IHNvdXJjZVBhdGggfSk7CiAgfSBjYXRjaCAoZXJyb3IpIHsKICAgIHByb2JsZW1zLnB1c2goYCR7c291cmNlUGF0aH0gc3ludGF4IGVycm9yOiAke2Vycm9yLm1lc3NhZ2V9YCk7CiAgfQp9Cgpmb3IgKGNvbnN0IG1hcmtlciBvZiBbCiAgJ2Z1bmN0aW9uIGZvcmdlUHVsc2UwNzhSdW5Tb3VyY2VSZWNvbmNpbGlhdGlvbigpJywKICAnZnVuY3Rpb24gZm9yZ2VQdWxzZTA3OENvbXBhcmVGaWxlc18obGl2ZUZpbGVzLCByZXBvRmlsZXMpJywKICAnZnVuY3Rpb24gZm9yZ2VQdWxzZTA3OEFzc2VydFdyaXRlckJvdW5kYXJ5Xyh0YXJnZXRzKScsCiAgImF1dGhvcml0eTogJ1JFUE8nIiwKICAiYXV0aG9yaXR5OiAnTElWRSciLAogICJyaWRlUmVxdWVzdHNXcml0ZXI6IHRydWUiLAogICdhcHBzU2NyaXB0SGVhZFdyaXRlczogMCcsCiAgJ3Byb2R1Y3Rpb25Ub3VjaGVkOiBmYWxzZScKXSkgewogIGlmICghc291cmNlLmluY2x1ZGVzKG1hcmtlcikpIHByb2JsZW1zLnB1c2goYE1pc3NpbmcgUFVMU0UtMDc4IG1hcmtlcjogJHttYXJrZXJ9YCk7Cn0KCmZvciAoY29uc3QgZm9yYmlkZGVuIG9mIFsKICAnZm9yZ2VVcGRhdGVTY3JpcHRDb250ZW50KCcsCiAgJ2ZvcmdlQ3JlYXRlVGVzdERlcGxveW1lbnQoJywKICAnZm9yZ2VTZXRBY3RpdmVFbmdpbmVTbG90KCcsCiAgJy9tZXJnZXMnLAogICdhdXRvbWF0aWNNZXJnZTogdHJ1ZScKXSkgewogIGlmIChzb3VyY2UuaW5jbHVkZXMoZm9yYmlkZGVuKSkgcHJvYmxlbXMucHVzaChgRm9yYmlkZGVuIFBVTFNFLTA3OCBtdXRhdGlvbiBtYXJrZXI6ICR7Zm9yYmlkZGVufWApOwp9Cgpjb25zdCBwcm9wZXJ0eVN0b3JlID0gbmV3IE1hcCgpOwpjb25zdCBjb250ZXh0ID0gewogIGNvbnNvbGUsCiAgRGF0ZSwKICBKU09OLAogIE9iamVjdCwKICBBcnJheSwKICBTdHJpbmcsCiAgTnVtYmVyLAogIEJvb2xlYW4sCiAgTWF0aCwKICBSZWdFeHAsCiAgRXJyb3IsCiAgZW5jb2RlVVJJQ29tcG9uZW50LAogIEJ1ZmZlciwKICBVdGlsaXRpZXM6IHsKICAgIENoYXJzZXQ6IHsgVVRGXzg6ICdVVEZfOCcgfSwKICAgIERpZ2VzdEFsZ29yaXRobTogeyBTSEFfMjU2OiAnU0hBXzI1NicgfSwKICAgIG5ld0Jsb2I6ICh2YWx1ZSkgPT4gKHsKICAgICAgZ2V0Qnl0ZXM6ICgpID0+IFsuLi5CdWZmZXIuZnJvbShTdHJpbmcodmFsdWUpLCAndXRmOCcpXQogICAgfSksCiAgICBjb21wdXRlRGlnZXN0OiAoX2FsZ29yaXRobSwgdmFsdWUpID0+IFsKICAgICAgLi4uY3J5cHRvLmNyZWF0ZUhhc2goJ3NoYTI1NicpLnVwZGF0ZShTdHJpbmcodmFsdWUpLCAndXRmOCcpLmRpZ2VzdCgpCiAgICBdCiAgfSwKICBQcm9wZXJ0aWVzU2VydmljZTogewogICAgZ2V0U2NyaXB0UHJvcGVydGllczogKCkgPT4gKHsKICAgICAgZ2V0UHJvcGVydHk6IChrZXkpID0+IHByb3BlcnR5U3RvcmUuZ2V0KGtleSkgPz8gbnVsbCwKICAgICAgc2V0UHJvcGVydHk6IChrZXksIHZhbHVlKSA9PiBwcm9wZXJ0eVN0b3JlLnNldChrZXksIFN0cmluZyh2YWx1ZSkpCiAgICB9KQogIH0KfTsKCmNvbnN0IHByZWx1ZGUgPSBgCmZ1bmN0aW9uIGZvcmdlQXNzZXJ0Xyhjb25kaXRpb24sIG1lc3NhZ2UpIHsKICBpZiAoIWNvbmRpdGlvbikgdGhyb3cgbmV3IEVycm9yKFN0cmluZyhtZXNzYWdlIHx8ICdhc3NlcnRpb24gZmFpbGVkJykpOwp9CmZ1bmN0aW9uIGZvcmdlU3RyaW5nXyh2YWx1ZSkgewogIHJldHVybiB2YWx1ZSA9PT0gbnVsbCB8fCB2YWx1ZSA9PT0gdW5kZWZpbmVkID8gJycgOiBTdHJpbmcodmFsdWUpOwp9CmZ1bmN0aW9uIGZvcmdlTm9ybWFsaXplVGV4dF8odmFsdWUpIHsKICByZXR1cm4gZm9yZ2VTdHJpbmdfKHZhbHVlKS5yZXBsYWNlKC9cXHJcXG4vZywgJ1xcbicpLnJlcGxhY2UoL1xcci9nLCAnXFxuJyk7Cn0KZnVuY3Rpb24gZm9yZ2VVdGY4Qnl0ZXNfKHZhbHVlKSB7CiAgcmV0dXJuIEJ1ZmZlci5mcm9tKGZvcmdlTm9ybWFsaXplVGV4dF8odmFsdWUpLCAndXRmOCcpLmxlbmd0aDsKfQpmdW5jdGlvbiBmb3JnZUhleF8oYnl0ZXMpIHsKICByZXR1cm4gYnl0ZXMubWFwKGZ1bmN0aW9uKGJ5dGUpIHsKICAgIGNvbnN0IHVuc2lnbmVkID0gYnl0ZSA8IDAgPyBieXRlICsgMjU2IDogYnl0ZTsKICAgIHJldHVybiAoJzAnICsgdW5zaWduZWQudG9TdHJpbmcoMTYpKS5zbGljZSgtMik7CiAgfSkuam9pbignJyk7Cn0KZnVuY3Rpb24gZm9yZ2VTaGEyNTZfKHZhbHVlKSB7CiAgcmV0dXJuIGZvcmdlSGV4XyhVdGlsaXRpZXMuY29tcHV0ZURpZ2VzdCgKICAgIFV0aWxpdGllcy5EaWdlc3RBbGdvcml0aG0uU0hBXzI1NiwKICAgIGZvcmdlTm9ybWFsaXplVGV4dF8odmFsdWUpLAogICAgVXRpbGl0aWVzLkNoYXJzZXQuVVRGXzgKICApKTsKfQpmdW5jdGlvbiBmb3JnZVN0YWJsZUpzb25fKHZhbHVlKSB7CiAgZnVuY3Rpb24gc29ydF8oaW5wdXQpIHsKICAgIGlmIChBcnJheS5pc0FycmF5KGlucHV0KSkgcmV0dXJuIGlucHV0Lm1hcChzb3J0Xyk7CiAgICBpZiAoaW5wdXQgJiYgT2JqZWN0LnByb3RvdHlwZS50b1N0cmluZy5jYWxsKGlucHV0KSA9PT0gJ1tvYmplY3QgT2JqZWN0XScpIHsKICAgICAgcmV0dXJuIE9iamVjdC5rZXlzKGlucHV0KS5zb3J0KCkucmVkdWNlKGZ1bmN0aW9uKG91dCwga2V5KSB7CiAgICAgICAgb3V0W2tleV0gPSBzb3J0XyhpbnB1dFtrZXldKTsKICAgICAgICByZXR1cm4gb3V0OwogICAgICB9LCB7fSk7CiAgICB9CiAgICByZXR1cm4gaW5wdXQ7CiAgfQogIHJldHVybiBKU09OLnN0cmluZ2lmeShzb3J0Xyh2YWx1ZSkpOwp9CmZ1bmN0aW9uIGZvcmdlQ2Fub25pY2FsRmlsZXNfKGZpbGVzKSB7CiAgY29uc3Qgbm9ybWFsaXplZCA9IChmaWxlcyB8fCBbXSkubWFwKGZ1bmN0aW9uKGZpbGUpIHsKICAgIHJldHVybiB7CiAgICAgIG5hbWU6IGZvcmdlU3RyaW5nXyhmaWxlLm5hbWUpLnRyaW0oKSwKICAgICAgdHlwZTogZm9yZ2VTdHJpbmdfKGZpbGUudHlwZSkudHJpbSgpLnRvVXBwZXJDYXNlKCksCiAgICAgIHNvdXJjZTogZm9yZ2VOb3JtYWxpemVUZXh0XyhmaWxlLnNvdXJjZSkKICAgIH07CiAgfSkuc29ydChmdW5jdGlvbihhLCBiKSB7CiAgICByZXR1cm4gYS5uYW1lLmxvY2FsZUNvbXBhcmUoYi5uYW1lKSB8fCBhLnR5cGUubG9jYWxlQ29tcGFyZShiLnR5cGUpOwogIH0pOwogIGNvbnN0IHNlZW4gPSB7fTsKICBub3JtYWxpemVkLmZvckVhY2goZnVuY3Rpb24oZmlsZSkgewogICAgY29uc3Qga2V5ID0gZmlsZS5uYW1lLnRvTG93ZXJDYXNlKCk7CiAgICBmb3JnZUFzc2VydF8oIXNlZW5ba2V5XSwgJ2R1cGxpY2F0ZSBmaWxlJyk7CiAgICBzZWVuW2tleV0gPSB0cnVlOwogIH0pOwogIHJldHVybiBub3JtYWxpemVkOwp9CmA7Cgp2bS5jcmVhdGVDb250ZXh0KGNvbnRleHQpOwp0cnkgewogIG5ldyB2bS5TY3JpcHQocHJlbHVkZSArICdcbicgKyBzb3VyY2UsIHsgZmlsZW5hbWU6ICdwdWxzZS0wNzgtY29tYmluZWQuZ3MnIH0pLnJ1bkluQ29udGV4dChjb250ZXh0KTsKICBjb25zdCByZXN1bHQgPSBjb250ZXh0LmZvcmdlUHVsc2UwNzhTZWxmVGVzdCgpOwogIGlmICghcmVzdWx0IHx8IHJlc3VsdC5vayAhPT0gdHJ1ZSkgewogICAgcHJvYmxlbXMucHVzaChgUFVMU0UtMDc4IHNlbGYtdGVzdCBmYWlsZWQ6ICR7SlNPTi5zdHJpbmdpZnkocmVzdWx0KX1gKTsKICB9Cn0gY2F0Y2ggKGVycm9yKSB7CiAgcHJvYmxlbXMucHVzaChgUFVMU0UtMDc4IG1vY2tlZCBleGVjdXRpb24gZmFpbGVkOiAke2Vycm9yLm1lc3NhZ2V9YCk7Cn0KCmNvbnN0IHJlcG9ydCA9IHsKICBvazogcHJvYmxlbXMubGVuZ3RoID09PSAwLAogIGNoZWNrZWRBdDogbmV3IERhdGUoKS50b0lTT1N0cmluZygpLAogIHByb2JsZW1zCn07CmNvbnNvbGUubG9nKEpTT04uc3RyaW5naWZ5KHJlcG9ydCwgbnVsbCwgMikpOwppZiAocHJvYmxlbXMubGVuZ3RoKSBwcm9jZXNzLmV4aXQoMSk7Cg==')
      },
      {
        path: taskPath,
        content: forgePulse078InstallerDecode_('ewogICJ0YXNrSWQiOiAiUFVMU0UtMDc4IiwKICAidGl0bGUiOiAiSW1wb3J0IGFuZCByZWNvbmNpbGUgZXZlcnkgbGl2ZSBQdWxzZSBBcHBzIFNjcmlwdCBwcm9qZWN0IiwKICAic3RhdHVzIjogIlBSX1JFQURZIiwKICAiYnVpbGRUeXBlIjogIkxJVkVfU09VUkNFX1JFQ09OQ0lMSUFUSU9OIiwKICAiZGVwZW5kc09uIjogWwogICAgIlBVTFNFLTA3NyIKICBdLAogICJzY29wZSI6IFsKICAgICJwdWxzZS1mb3JnZS9jb250cm9sbGVyL1BVTFNFMDc4U291cmNlUmVjb25jaWxpYXRpb24uZ3MiLAogICAgInB1bHNlLWZvcmdlL3Rlc3RzL3ZhbGlkYXRlLXB1bHNlLTA3OC5tanMiLAogICAgInB1bHNlLWZvcmdlL3JlY29uY2lsaWF0aW9uL1BVTFNFLTA3OCIsCiAgICAicHVsc2UtYXV0b2J1aWxkL3JlcXVlc3QtYXBwIiwKICAgICJhcHBzLXNjcmlwdC9ob3ktZHJpdmVyLW9zLXdyaXRlciIsCiAgICAicHVsc2UtYXV0b2J1aWxkL3J1bnRpbWUiCiAgXSwKICAidGFyZ2V0cyI6IHsKICAgICJmb3JnZUNvbnRyb2xsZXIiOiAiY3VycmVudCBjb250cm9sbGVyIFNjcmlwdEFwcCBwcm9qZWN0IiwKICAgICJob3lEcml2ZXIiOiAiMXNON01GcnpFT0QwR01JT2MxMFhvQThqNUlQelp3UXlub3dJdVpwWERDV3VMYkYyd3FJRGY4WmowIiwKICAgICJyZXF1ZXN0QXBwIjogIjFweEYtdHFsdS1OcklOdjBRRC1zUVpFWE1HVW9jNDA4WWhIT3VLY2NvVV9VUkN0Q3lPbVRpYVZTbSIsCiAgICAicmlkZXJTdGF0dXNSdW50aW1lIjogIjFjQUJJenYwajhwb1lHeTNoVmJjbUtlLURCdUpRSFI5SGNqLTJsOVZxdlhNb3Rfa21sZUtuSGdVZiIKICB9LAogICJhY2NlcHRhbmNlIjogewogICAgImNvbXBsZXRlTGl2ZVNvdXJjZVJlYWQiOiB0cnVlLAogICAgInBlckZpbGVTdGF0dXNlcyI6IFsKICAgICAgIk1BVENIIiwKICAgICAgIkRJRkYiLAogICAgICAiTElWRV9PTkxZIiwKICAgICAgIlJFUE9fT05MWSIKICAgIF0sCiAgICAiaW1tdXRhYmxlU25hcHNob3RzQW5kSGFzaGVzIjogdHJ1ZSwKICAgICJyZXZpZXdlZEdpdEh1YlJlcGFpck9ubHkiOiB0cnVlLAogICAgInJlcXVlc3RBcHBPbmx5UmlkZVJlcXVlc3RzV3JpdGVyIjogdHJ1ZSwKICAgICJjb250cm9sbGVyUmVwb1ByZWZlcnJlZCI6IHRydWUsCiAgICAibGl2ZUFwcHNQcmVmZXJyZWQiOiB0cnVlLAogICAgImFwcHNTY3JpcHRIZWFkV3JpdGVzIjogMCwKICAgICJhdXRvbWF0aWNNZXJnZSI6IGZhbHNlLAogICAgImF1dG9tYXRpY1Byb2R1Y3Rpb25EZXBsb3ltZW50IjogZmFsc2UsCiAgICAiYXV0b21hdGljRW5naW5lQWN0aXZhdGlvbiI6IGZhbHNlLAogICAgInByb2R1Y3Rpb25EYXRhQ2hhbmdlZCI6IGZhbHNlCiAgfQp9Cg==')
      },
      {
        path: packagePath,
        content: JSON.stringify(packageJson, null, 2) + '\n'
      }
    ]
  });

  console.log(JSON.stringify(result, null, 2));
  return result;
}

function forgePulse078InstallerReadRepoText_(path, ref) {
  const encodedPath = forgeString_(path).split('/').map(encodeURIComponent).join('/');
  const result = forgeGitHubApi_(
    '/contents/' + encodedPath + '?ref=' + encodeURIComponent(ref || 'main'),
    { method: 'get' }
  );
  forgeAssert_(
    result && result.content && result.encoding === 'base64',
    'GitHub file content was not returned for ' + path
  );
  return forgePulse078InstallerDecode_(
    forgeString_(result.content).replace(/\s/g, '')
  );
}

function forgePulse078InstallerDecode_(encoded) {
  return Utilities.newBlob(
    Utilities.base64Decode(forgeString_(encoded).replace(/\s/g, ''))
  ).getDataAsString('UTF-8');
}



/**
 * PULSE-078 — read-only live-source reconciliation.
 *
 * Reads complete Apps Script HEAD source, compares it with GitHub, captures
 * immutable per-file hashes and source snapshots, and opens a reviewed PR.
 * It never writes Apps Script HEAD, creates a deployment, activates an engine,
 * merges a PR, or changes production data.
 */

const FORGE_PULSE078_TASK_ID_ = 'PULSE-078';
const FORGE_PULSE078_LATEST_RECEIPT_KEY_ = 'PULSE_FORGE_PULSE078_LATEST_RECEIPT';
const FORGE_PULSE078_RECEIPT_PREFIX_ = 'PULSE_FORGE_PULSE078_RECEIPT_';

function forgePulse078Targets_() {
  return [
    {
      alias: 'FORGE_CONTROLLER',
      scriptId: ScriptApp.getScriptId(),
      repoRoots: ['pulse-forge/core/', 'pulse-forge/controller/'],
      repoExact: ['pulse-forge/appsscript.json'],
      canonicalRoot: 'pulse-forge/controller',
      authority: 'REPO',
      rideRequestsWriter: false,
      importLiveOnly: false,
      controllerProject: true
    },
    {
      alias: 'HOY_DRIVER',
      scriptId: '1sN7MFrzEOD0GMIOc10XoA8j5IPzZwQynowIuZpXDCWuLbF2wqIDf8Zj0',
      repoRoots: ['apps-script/hoy-driver-os-writer/'],
      repoExact: [],
      canonicalRoot: 'apps-script/hoy-driver-os-writer',
      authority: 'LIVE',
      rideRequestsWriter: false,
      importLiveOnly: true,
      controllerProject: false
    },
    {
      alias: 'PULSE_REQUEST_APP',
      scriptId: '1pxF-tqlu-NrINv0QD-sQZEXMGUoc408YhHOuKccoU_URCtCyOmTiaVSm',
      repoRoots: ['pulse-autobuild/request-app/'],
      repoExact: [],
      canonicalRoot: 'pulse-autobuild/request-app',
      authority: 'LIVE',
      rideRequestsWriter: true,
      importLiveOnly: true,
      controllerProject: false
    },
    {
      alias: 'RIDER_STATUS_RUNTIME',
      scriptId: '1cABIzv0j8poYGy3hVbcmKe-DBuJQHR9Hcj-2l9VqvXMot_kmleKnHgUf',
      repoRoots: ['pulse-autobuild/runtime/'],
      repoExact: [],
      canonicalRoot: 'pulse-autobuild/runtime',
      authority: 'LIVE',
      rideRequestsWriter: false,
      importLiveOnly: true,
      controllerProject: false
    }
  ];
}

function forgePulse078AssertWriterBoundary_(targets) {
  const writers = (targets || []).filter(function(target) {
    return target.rideRequestsWriter === true;
  });
  forgeAssert_(writers.length === 1, 'Exactly one Ride Requests writer must be declared.');
  forgeAssert_(
    writers[0].alias === 'PULSE_REQUEST_APP',
    'The standalone Pulse Request App must remain the only Ride Requests writer.'
  );
  return {
    ok: true,
    authorizedWriterAlias: writers[0].alias,
    additionalWritersDeclared: false
  };
}

function forgePulse078FileIdentity_(file) {
  return forgeString_(file.name).toLowerCase() + '::' + forgeString_(file.type).toUpperCase();
}

function forgePulse078Extension_(type) {
  const normalized = forgeString_(type).toUpperCase();
  if (normalized === 'SERVER_JS') return '.gs';
  if (normalized === 'HTML') return '.html';
  if (normalized === 'JSON') return '.json';
  throw new Error('Unsupported Apps Script file type: ' + normalized);
}

function forgePulse078RepoIdentityFromPath_(path) {
  const clean = forgeString_(path).replace(/^\/+/, '');
  const base = clean.split('/').pop();
  if (base === 'appsscript.json') {
    return { name: 'appsscript', type: 'JSON', path: clean };
  }
  if (/\.gs$/i.test(base)) {
    return { name: base.replace(/\.gs$/i, ''), type: 'SERVER_JS', path: clean };
  }
  if (/\.html$/i.test(base)) {
    return { name: base.replace(/\.html$/i, ''), type: 'HTML', path: clean };
  }
  return null;
}

function forgePulse078CanonicalPath_(target, file) {
  if (forgeString_(file.name).toLowerCase() === 'appsscript' &&
      forgeString_(file.type).toUpperCase() === 'JSON') {
    return target.controllerProject
      ? 'pulse-forge/appsscript.json'
      : target.canonicalRoot.replace(/\/+$/, '') + '/appsscript.json';
  }

  const extension = forgePulse078Extension_(file.type);
  if (target.controllerProject) {
    const coreNames = {
      ForgeCore: true,
      ForgeRegistry: true,
      ForgeValidator: true,
      ForgeProjectApi: true,
      ForgeGitHub: true,
      ForgeEngine: true,
      ForgeReconcile: true
    };
    const folder = coreNames[file.name] ? 'pulse-forge/core' : 'pulse-forge/controller';
    return folder + '/' + file.name + extension;
  }
  return target.canonicalRoot.replace(/\/+$/, '') + '/' + file.name + extension;
}

function forgePulse078SnapshotPath_(captureId, alias, file) {
  const safeAlias = forgeString_(alias).replace(/[^A-Za-z0-9_-]/g, '_');
  const extension = forgePulse078Extension_(file.type);
  const name = forgeString_(file.name).replace(/[^A-Za-z0-9_.-]/g, '_');
  return 'pulse-forge/reconciliation/PULSE-078/' +
    captureId + '/' + safeAlias + '/live/' + name + extension;
}

function forgePulse078CompareFiles_(liveFiles, repoFiles) {
  const live = forgeCanonicalFiles_(liveFiles || []);
  const repo = (repoFiles || []).map(function(file) {
    return {
      name: forgeString_(file.name),
      type: forgeString_(file.type).toUpperCase(),
      source: forgeNormalizeText_(file.source),
      path: forgeString_(file.path)
    };
  }).sort(function(a, b) {
    return forgePulse078FileIdentity_(a).localeCompare(forgePulse078FileIdentity_(b));
  });

  const liveByKey = {};
  const repoByKey = {};

  live.forEach(function(file) {
    const key = forgePulse078FileIdentity_(file);
    forgeAssert_(!liveByKey[key], 'Duplicate live file identity: ' + key);
    liveByKey[key] = file;
  });
  repo.forEach(function(file) {
    const key = forgePulse078FileIdentity_(file);
    forgeAssert_(!repoByKey[key], 'Duplicate repository file identity: ' + key);
    repoByKey[key] = file;
  });

  const keys = Object.keys(Object.assign({}, liveByKey, repoByKey)).sort();
  return keys.map(function(key) {
    const liveFile = liveByKey[key] || null;
    const repoFile = repoByKey[key] || null;
    const liveSha = liveFile ? forgeSha256_(liveFile.source) : '';
    const repoSha = repoFile ? forgeSha256_(repoFile.source) : '';
    let status = 'MATCH';
    if (liveFile && !repoFile) status = 'LIVE_ONLY';
    else if (!liveFile && repoFile) status = 'REPO_ONLY';
    else if (liveSha !== repoSha) status = 'DIFF';

    return {
      key: key,
      name: (liveFile || repoFile).name,
      type: (liveFile || repoFile).type,
      status: status,
      liveSha256: liveSha,
      repoSha256: repoSha,
      repoPath: repoFile ? repoFile.path : '',
      liveBytes: liveFile ? forgeUtf8Bytes_(liveFile.source) : 0,
      repoBytes: repoFile ? forgeUtf8Bytes_(repoFile.source) : 0
    };
  });
}

function forgePulse078RepoTree_(ref) {
  const branch = forgeString_(ref || 'main');
  const tree = forgeGitHubApi_(
    '/git/trees/' + encodeURIComponent(branch) + '?recursive=1',
    { method: 'get' }
  );
  forgeAssert_(tree && Array.isArray(tree.tree), 'GitHub repository tree was not returned.');
  forgeAssert_(tree.truncated !== true, 'GitHub repository tree was truncated; reconciliation stopped.');
  return tree.tree;
}

function forgePulse078PathIncluded_(target, path) {
  const clean = forgeString_(path);
  if ((target.repoExact || []).indexOf(clean) >= 0) return true;
  return (target.repoRoots || []).some(function(root) {
    return clean.indexOf(root) === 0;
  });
}

function forgePulse078ReadRepoText_(path, ref) {
  const encoded = forgeString_(path).split('/').map(encodeURIComponent).join('/');
  const result = forgeGitHubApi_(
    '/contents/' + encoded + '?ref=' + encodeURIComponent(ref || 'main'),
    { method: 'get' }
  );
  forgeAssert_(
    result && result.encoding === 'base64' && result.content,
    'GitHub source was not returned for ' + path
  );
  const compact = forgeString_(result.content).replace(/\s/g, '');
  return Utilities.newBlob(Utilities.base64Decode(compact)).getDataAsString('UTF-8');
}

function forgePulse078RepoFilesForTarget_(target, tree, ref) {
  const files = [];
  (tree || []).forEach(function(entry) {
    if (!entry || entry.type !== 'blob') return;
    if (!forgePulse078PathIncluded_(target, entry.path)) return;
    const identity = forgePulse078RepoIdentityFromPath_(entry.path);
    if (!identity) return;
    files.push({
      name: identity.name,
      type: identity.type,
      path: identity.path,
      source: forgePulse078ReadRepoText_(identity.path, ref)
    });
  });

  const seen = {};
  files.forEach(function(file) {
    const key = forgePulse078FileIdentity_(file);
    forgeAssert_(!seen[key], 'Repository maps multiple files to Apps Script identity ' + key);
    seen[key] = true;
  });
  return files;
}

function forgePulse078LiveFileMap_(files) {
  const map = {};
  forgeCanonicalFiles_(files || []).forEach(function(file) {
    map[forgePulse078FileIdentity_(file)] = file;
  });
  return map;
}

function forgePulse078RepoFileMap_(files) {
  const map = {};
  (files || []).forEach(function(file) {
    map[forgePulse078FileIdentity_(file)] = file;
  });
  return map;
}

function forgePulse078ActionFor_(target, comparison) {
  if (comparison.status === 'MATCH') return 'NO_CHANGE';
  if (comparison.status === 'REPO_ONLY') return 'KEEP_REPO';
  if (target.authority === 'REPO' && comparison.status === 'DIFF') {
    return 'REVIEW_REPO_PREFERRED';
  }
  if (comparison.status === 'LIVE_ONLY' && target.importLiveOnly !== true) {
    return 'SNAPSHOT_ONLY';
  }
  return 'PROPOSE_LIVE_TO_CANONICAL';
}

function forgePulse078PutPrFile_(fileMap, path, content) {
  const clean = forgeString_(path).replace(/^\/+/, '');
  forgeAssert_(clean, 'PR file path is required.');
  const normalized = forgeNormalizeText_(content);
  if (Object.prototype.hasOwnProperty.call(fileMap, clean)) {
    forgeAssert_(fileMap[clean] === normalized, 'Conflicting generated PR content for ' + clean);
    return;
  }
  fileMap[clean] = normalized;
}

function forgePulse078RunSourceReconciliation() {
  return forgeWithBuildLock_(function() {
    const targets = forgePulse078Targets_();
    const writerBoundary = forgePulse078AssertWriterBoundary_(targets);
    const ref = 'main';
    const tree = forgePulse078RepoTree_(ref);
    const captureId = Utilities.formatDate(
      new Date(),
      Session.getScriptTimeZone() || 'America/New_York',
      'yyyyMMdd-HHmmss'
    );

    const prFiles = {};
    const targetReports = [];
    let proposedCanonicalChanges = 0;

    targets.forEach(function(target) {
      const live = forgeGetScriptContent(target.scriptId);
      const repoFiles = forgePulse078RepoFilesForTarget_(target, tree, ref);
      const comparisons = forgePulse078CompareFiles_(live.files, repoFiles);
      const liveMap = forgePulse078LiveFileMap_(live.files);
      const repoMap = forgePulse078RepoFileMap_(repoFiles);

      live.files.forEach(function(file) {
        forgePulse078PutPrFile_(
          prFiles,
          forgePulse078SnapshotPath_(captureId, target.alias, file),
          file.source
        );
      });

      const fileReports = comparisons.map(function(comparison) {
        const action = forgePulse078ActionFor_(target, comparison);
        const liveFile = liveMap[comparison.key] || null;
        const repoFile = repoMap[comparison.key] || null;
        let canonicalPath = repoFile ? repoFile.path : '';

        if (action === 'PROPOSE_LIVE_TO_CANONICAL') {
          forgeAssert_(liveFile, 'Live source is required for canonical import.');
          canonicalPath = canonicalPath || forgePulse078CanonicalPath_(target, liveFile);
          forgePulse078PutPrFile_(prFiles, canonicalPath, liveFile.source);
          proposedCanonicalChanges += 1;
        }

        return Object.assign({}, comparison, {
          action: action,
          canonicalPath: canonicalPath
        });
      });

      const inventory = {
        taskId: FORGE_PULSE078_TASK_ID_,
        captureId: captureId,
        alias: target.alias,
        scriptId: target.scriptId,
        authority: target.authority,
        rideRequestsWriter: target.rideRequestsWriter === true,
        livePackageHash: live.packageHash,
        liveInventory: live.inventory,
        repositoryFiles: repoFiles.map(function(file) {
          return {
            path: file.path,
            name: file.name,
            type: file.type,
            bytes: forgeUtf8Bytes_(file.source),
            sha256: forgeSha256_(file.source)
          };
        }),
        files: fileReports,
        productionProjectMutated: false
      };
      const inventoryPath = 'pulse-forge/reconciliation/PULSE-078/' +
        captureId + '/' + target.alias + '/inventory.json';
      forgePulse078PutPrFile_(prFiles, inventoryPath, JSON.stringify(inventory, null, 2) + '\n');

      targetReports.push(inventory);
    });

    const counts = { MATCH: 0, DIFF: 0, LIVE_ONLY: 0, REPO_ONLY: 0 };
    targetReports.forEach(function(target) {
      target.files.forEach(function(file) {
        counts[file.status] += 1;
      });
    });

    const report = {
      taskId: FORGE_PULSE078_TASK_ID_,
      captureId: captureId,
      capturedAt: forgeNowIso_(),
      repository: forgeGitHubRepository_(),
      repositoryRef: ref,
      writerBoundary: writerBoundary,
      targets: targetReports,
      counts: counts,
      proposedCanonicalChanges: proposedCanonicalChanges,
      appsScriptHeadWrites: 0,
      deploymentsCreated: 0,
      engineActivations: 0,
      productionDataChanged: false,
      automaticMerge: false,
      productionTouched: false
    };
    report.reportHash = forgeSha256_(forgeStableJson_(report));

    const basePath = 'pulse-forge/reconciliation/PULSE-078/' + captureId;
    forgePulse078PutPrFile_(
      prFiles,
      basePath + '/report.json',
      JSON.stringify(report, null, 2) + '\n'
    );
    forgePulse078PutPrFile_(
      prFiles,
      basePath + '/README.md',
      [
        '# PULSE-078 live-source reconciliation',
        '',
        '- Capture: `' + captureId + '`',
        '- Report hash: `' + report.reportHash + '`',
        '- MATCH: ' + counts.MATCH,
        '- DIFF: ' + counts.DIFF,
        '- LIVE_ONLY: ' + counts.LIVE_ONLY,
        '- REPO_ONLY: ' + counts.REPO_ONLY,
        '- Proposed canonical changes: ' + proposedCanonicalChanges,
        '- Authorized Ride Requests writer: `PULSE_REQUEST_APP`',
        '- Apps Script HEAD writes: 0',
        '- Deployments: 0',
        '- Production data changes: none',
        '',
        'Controller drift remains repository-preferred. Live application drift is proposed',
        'through this reviewed PR. Every complete live source file is also preserved under',
        'the capture folder before any canonical source change is reviewed.',
        ''
      ].join('\n')
    );

    const stamp = captureId;
    const pull = forgeGitHubCreatePullRequest({
      baseBranch: 'main',
      headBranch: 'pulse/pulse-078-source-reconciliation-' + stamp,
      title: 'PULSE-078: Reconcile live Pulse Apps Script source',
      commitMessage: 'Capture and reconcile live Pulse Apps Script source',
      body: [
        '## PULSE-078 source reconciliation',
        '',
        'Reads complete live source for the Forge controller, Hoy Driver, standalone',
        'request app, and Runtime Lite/rider-status project.',
        '',
        '### Evidence',
        '- Immutable live source snapshots and SHA-256 inventories',
        '- Per-file MATCH / DIFF / LIVE_ONLY / REPO_ONLY classification',
        '- Repository-preferred controller drift handling',
        '- Live-preferred application drift proposed through review',
        '- Standalone request app remains the only declared Ride Requests writer',
        '',
        '### Safety',
        '- No Apps Script HEAD writes',
        '- No deployments',
        '- No engine activation',
        '- No automatic merge',
        '- No production data mutation',
        '',
        'Report hash: `' + report.reportHash + '`'
      ].join('\n'),
      files: Object.keys(prFiles).sort().map(function(path) {
        return { path: path, content: prFiles[path] };
      })
    });

    const receiptIdentity = {
      taskId: FORGE_PULSE078_TASK_ID_,
      captureId: captureId,
      reportHash: report.reportHash,
      commitSha: pull.commitSha,
      pullRequestNumber: pull.pullRequest.number
    };
    const receiptId = forgeSha256_(forgeStableJson_(receiptIdentity));
    const receipt = Object.assign({}, receiptIdentity, {
      receiptId: receiptId,
      ok: true,
      pullRequestUrl: pull.pullRequest.url,
      counts: counts,
      proposedCanonicalChanges: proposedCanonicalChanges,
      writerBoundary: writerBoundary,
      appsScriptHeadWrites: 0,
      productionTouched: false,
      automaticMerge: false,
      createdAt: forgeNowIso_()
    });

    const props = PropertiesService.getScriptProperties();
    props.setProperty(FORGE_PULSE078_RECEIPT_PREFIX_ + receiptId, forgeStableJson_(receipt));
    props.setProperty(FORGE_PULSE078_LATEST_RECEIPT_KEY_, receiptId);

    console.log(JSON.stringify(receipt, null, 2));
    return receipt;
  });
}

function forgePulse078SelfTest() {
  const live = [
    { name: 'A', type: 'SERVER_JS', source: 'same' },
    { name: 'B', type: 'HTML', source: 'live-diff' },
    { name: 'C', type: 'SERVER_JS', source: 'live-only' }
  ];
  const repo = [
    { name: 'A', type: 'SERVER_JS', source: 'same', path: 'A.gs' },
    { name: 'B', type: 'HTML', source: 'repo-diff', path: 'B.html' },
    { name: 'D', type: 'JSON', source: '{}', path: 'D.json' }
  ];
  const statuses = forgePulse078CompareFiles_(live, repo).map(function(item) {
    return item.status;
  }).sort();

  const boundary = forgePulse078AssertWriterBoundary_([
    { alias: 'PULSE_REQUEST_APP', rideRequestsWriter: true },
    { alias: 'HOY_DRIVER', rideRequestsWriter: false }
  ]);

  return {
    ok: forgeStableJson_(statuses) === forgeStableJson_(['DIFF', 'LIVE_ONLY', 'MATCH', 'REPO_ONLY']) &&
      boundary.ok === true &&
      forgePulse078CanonicalPath_(
        { controllerProject: false, canonicalRoot: 'example' },
        { name: 'Code', type: 'SERVER_JS' }
      ) === 'example/Code.gs',
    statuses: statuses,
    writerBoundary: boundary,
    writesPerformed: false,
    productionTouched: false
  };
}
