[build]
  publish = "."
[[redirects]]
  from = "/whats-up"
  to = "/whats-up.html"
  status = 200
[[redirects]]
  from = "/access"
  to = "/access.html"
  status = 200
[[redirects]]
  from = "/ride-status"
  to = "/ride-status.html"
  status = 200
